================================

1.2.1:

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

================================


In [118]:
import numpy as np
x = np.array([[1, 2],[3, 4],[5, 6],[7, 8], [9, 10]])
print("Array: ")
print(x)
print("4 строка 2 элем: ")
print(x[3][1])
print("2 строка: ")
print(x[1])

Array: 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
4 строка 2 элем: 
8
2 строка: 
[3 4]


================================

1.3.1:

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

================================

In [145]:
import numpy as np
"""

arr = np.array([[1, 0, 1, 0, 1, 0, 1, 0],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [1, 0, 1, 0, 1, 0, 1, 0],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [1, 0, 1, 0, 1, 0, 1, 0],
                [0, 1, 0, 1, 0, 1, 0, 1],
                [1, 0, 1, 0, 1, 0, 1, 0],
                [0, 1, 0, 1, 0, 1, 0, 1]])
print(arr)
"""

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


================================

1.2.2 Пример:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

================================

In [120]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.3.2 Задание:

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.


In [121]:
import numpy as np

arr = np.empty((5,5))
#arr = np.zeros((5,5))
#print(arr)
for i in range(5):
    arr[[i]] = np.arange(0,5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [122]:
import numpy as np
Z = np.random.random((10, 10))
#print(Z)
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.007996143184181737 0.9872342910855099 0.5164007647753658


1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.


In [123]:
import numpy as np

arr = np.random.random((3,3,3))
print(arr)

[[[0.51348539 0.68422411 0.72199294]
  [0.98766275 0.6068465  0.44426069]
  [0.35716602 0.12341448 0.90320669]]

 [[0.46632087 0.72615788 0.39394853]
  [0.35609053 0.45662112 0.5531104 ]
  [0.34423153 0.62725106 0.9104717 ]]

 [[0.05791011 0.73655525 0.00099835]
  [0.65065847 0.66037166 0.81661379]
  [0.33446852 0.36786984 0.96844949]]]


1.2.4 Пример:

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [124]:
A = np.arange(25).reshape(5,5)
print("Исходный: ")
print(A)
A [[0,1]] = A[[1,0]]
print("Поменяли местами: ")
print(A)

Исходный: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Поменяли местами: 
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.


In [125]:
import numpy as np

column = 7
line = 7
arr = np.zeros((column, line))
#print(arr)
arr[0] = np.ones(line)
arr[line-1] = np.ones(line)
#print(arr)
#print(arr[[1]])
#print(arr[2,1])
for i in range(0, column-1):
    arr[i, 0] = 1
for i in range(0, column-1):
    arr[i, column - 1] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


1.2.5 Пример

Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

В Python, NumPy с последней версией, где nan-это значение только для плавающих массивов,
 которое означает not a number и является числовым типом данных,
  который используется для представления неопределенного значения

In [126]:
import numpy as np

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


1.2.6 Пример:
Отсортировать массив.


In [127]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.5 Пример:
Создайте массив и отсортируйте его по убыванию.

In [128]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr[::-1])

[8 6 4 7 3 5 1 2]


1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [129]:
x = np.ndarray((3, 5))
np.shape(x), np.size(x)

((3, 5), 15)

========================================================
БИБЛИОТЕКА PANDAS
========================================================

2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [130]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)


0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [131]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5],['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])

1


2.2.3 Пример

Создайте новый фрейм данных.


In [132]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Уелс', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0        Джеки Уелс       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv


In [133]:
import pandas as pd

url =   "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)
#dataframe.tail(3) - конец таблицы
#dataframe.shape - форма таблицы

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [134]:
import pandas as pd

dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [135]:
import pandas as pd

url = "D:/MY_PROJECTS/dsProject/ArtificialIntelligence/frost.csv"

dataframe = pd.read_csv(url)

dataframe
dataframe[dataframe['Количество наград (+)'] > 10]

Название музыкальных групп  Количество альбомов (+)  \
0                Linkin Park                       56   
1                 Papa Roach                       62   
2                      AC/DC                       41   
4            Imagine Dragons                       42   
6               Король и Шут                       19   
8                    Nirvana                       39   

   Количество прослушиваний за месяц (+)  Количество наград (+)  \
0                                2010488                     48   
1                                 720816                     26   
2                                 385686                     18   
4                                2956234                     49   
6                                3118323                     12   
8                                1262902                     17   

   Количество фолловеров (+)  Релиз последнего альбома от нашего года (-)  
0                    3431246                                            6  
1                     869121                                            4  
2                    2138734                                            3  
4                    4353698                                            5  
6                         11                                           11  
8                         32                                           32

2.3.1 - 2.3.3 СДЕЛАТЬ С ИНЕТОМ

2.3.1:
Пример: Найти евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [136]:
import pandas as pd
from math import sqrt
A = [70, 40]
B = [330, 228]

s1 = pd.Series(A)
s2 = pd.Series(B)

dist = sqrt( (s1[0] - s2[0])**2 + (s1[1] - s1[1])**2 )
print(dist)

260.0


2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [137]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')
df

state_fips    state state_abbr zipcode      county        city
0               1  Alabama         AL   35004   St. Clair       Acmar
1               1  Alabama         AL   35005   Jefferson  Adamsville
2               1  Alabama         AL   35006   Jefferson       Adger
3               1  Alabama         AL   35007      Shelby    Keystone
4               1  Alabama         AL   35010  Tallapoosa    New site
...           ...      ...        ...     ...         ...         ...
33098          56  Wyoming         WY   83126     Lincoln       Smoot
33099          56  Wyoming         WY   83127     Lincoln      Thayne
33100          56  Wyoming         WY   83128     Lincoln      Alpine
33101          56  Wyoming         WY   831HH     Lincoln  Zcta 831hh
33102          56  Wyoming         WY   831XX     Lincoln  Zcta 831xx

[33103 rows x 6 columns]

In [138]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')

print(df.head(2), df.tail(3), df.shape, df.describe(), sep="\n\n")

   state_fips    state state_abbr zipcode     county        city
0           1  Alabama         AL   35004  St. Clair       Acmar
1           1  Alabama         AL   35005  Jefferson  Adamsville

       state_fips    state state_abbr zipcode   county        city
33100          56  Wyoming         WY   83128  Lincoln      Alpine
33101          56  Wyoming         WY   831HH  Lincoln  Zcta 831hh
33102          56  Wyoming         WY   831XX  Lincoln  Zcta 831xx

(33103, 6)

         state_fips
count  33103.000000
mean      29.780533
std       15.291582
min        1.000000
25%       18.000000
50%       29.000000
75%       42.000000
max       56.000000


========================================================
3.1. Теоретический материал – Работа с числовыми данными
========================================================

3.2.1. Пример


In [139]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])

minmax_scale = preprocessing.MinMaxScaler (feature_range = (0,1))

scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2. Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.


In [140]:
import numpy as np
from sklearn import preprocessing
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

standardized

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


3.2.3. Пример

Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [141]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame(
    {
        'A':[14.00,90.20,90.95,96.27,91.21],
        'B':[103.02,107.26,110.35,114.23,114.68],
        'C':['big','small','big','small','small'],
    }
)
dfTest [['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [142]:
import pandas as pd

new_df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
new_df.head(4)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa

In [143]:
import pandas as pd
from sklearn import preprocessing

new_df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
new_df.head(4)

scaler = preprocessing.MinMaxScaler()
col_name = "sepal_length_cm"
new_df[col_name] = scaler.fit_transform(new_df[[col_name, col_name]])
new_df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222             3.5              1.4             0.2   
1           0.166667             3.0              1.4             0.2   
2           0.111111             3.2              1.3             0.2   
3           0.083333             3.1              1.5             0.2   
4           0.194444             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667             3.0              5.2             2.3   
146         0.555556             2.5              5.0             1.9   
147         0.611111             3.0              5.2             2.0   
148         0.527778             3.4              5.4             2.3   
149         0.444444             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [144]:
import pandas as pd
from sklearn import preprocessing

new_df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
new_df.head(4)

scaler = preprocessing.StandardScaler()
col_name = "sepal_width_cm"
new_df[col_name] = scaler.fit_transform(new_df[[col_name, col_name]])
new_df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1        1.032057              1.4             0.2   
1                4.9       -0.124958              1.4             0.2   
2                4.7        0.337848              1.3             0.2   
3                4.6        0.106445              1.5             0.2   
4                5.0        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7       -0.124958              5.2             2.3   
146              6.3       -1.281972              5.0             1.9   
147              6.5       -0.124958              5.2             2.0   
148              6.2        0.800654              5.4             2.3   
149              5.9       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]